[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vapor-ram"
version = "1.0.1"
description = "Ultra-Low RAM SSD Streaming Engine for google/gemma-4-E4B-it (< 1.5 GB RAM)"
readme = "README.md"
authors = [
    { name = "Sudeepta Sarkar (sudsarkar13)", email = "sudsarkar13@gmail.com" }
]
license = "Apache-2.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
]
dependencies = [
    "numpy>=1.20.0",
]

[project.scripts]
vapor = "vapor:main"

[project.urls]
Homepage = "https://github.com/sudsarkar13/vapor-ram"
